#ifndef CONFIG_CLI_H_
#define CONFIG_CLI_H_

#ifndef OPENVC_CONFIG_CLI_MAX_LINE_LENGTH
#define OPENVC_CONFIG_CLI_MAX_LINE_LENGTH 128
#endif

#ifndef OPENVC_CONFIG_CLI_UART_RX_BUFFER_SIZE
#define OPENVC_CONFIG_CLI_UART_RX_BUFFER_SIZE 512
#endif

#ifndef OPENVC_CONFIG_CLI_UART_TX_BUFFER_SIZE
#define OPENVC_CONFIG_CLI_UART_TX_BUFFER_SIZE 1024
#endif

#endif /* CONFIG_CLI_H_ */
