#ifndef CONFIG_LOGGING_H_
#define CONFIG_LOGGING_H_

#ifndef OPENVC_CONFIG_LOG_OUTPUT
#define OPENVC_CONFIG_LOG_OUTPUT OPENVC_CONFIG_LOG_OUTPUT_PLATFORM_DEFINED
#endif

#define OPENVC_CONFIG_LOG_OUTPUT_NONE 0
#define OPENVC_CONFIG_LOG_OUTPUT_DEBUG_UART 1
#define OPENVC_CONFIG_LOG_OUTPUT_APP 2
#define OPENVC_CONFIG_LOG_OUTPUT_PLATFORM_DEFINED 3

#ifndef OPENVC_CONFIG_LOG_LEVEL
#define OPENVC_CONFIG_LOG_LEVEL VC_LOG_LEVEL_CRIT
#endif

#ifndef OPENVC_CONFIG_DYNAMIC_LOG_LEVEL_ENABLE
#define OPENVC_CONFIG_DYNAMIC_LOG_LEVEL_ENABLE 0
#endif

#ifndef OPENVC_CONFIG_LOG_API
#define OPENVC_CONFIG_LOG_API 1
#endif

#ifndef OPENVC_CONFIG_LOG_MEM
#define OPENVC_CONFIG_LOG_MEM 1
#endif

#ifndef OPENVC_CONFIG_LOG_PLATFORM
#define OPENVC_CONFIG_LOG_PLATFORM 0
#endif

#ifndef OPENVC_CONFIG_LOG_CLI
#define OPENVC_CONFIG_LOG_CLI 1
#endif

#ifndef OPENVC_CONFIG_LOG_CORE
#define OPENVC_CONFIG_LOG_CORE 1
#endif

#ifndef OPENVC_CONFIG_LOG_UTIL
#define OPENVC_CONFIG_LOG_UTIL 1
#endif

#ifndef OPENVC_CONFIG_LOG_PREPEND_LEVEL
#define OPENVC_CONFIG_LOG_PREPEND_LEVEL 1
#endif

#ifndef OPENVC_CONFIG_LOG_PREPEND_REGION
#define OPENVC_CONFIG_LOG_PREPEND_REGION 1
#endif

#ifndef OPENVC_CONFIG_LOG_SUFFIX
#define OPENVC_CONFIG_LOG_SUFFIX ""
#endif

#ifndef OPENVC_CONFIG_PLAT_LOG_FUNCTION
#define OPENVC_CONFIG_PLAT_LOG_FUNCTION vcPlatLog
#endif

#endif /* CONFIG_LOGGING_H_ */
