#ifndef OPENVC_CORE_DEFAULT_CONFIG_H_
#define OPENVC_CORE_DEFAULT_CONFIG_H_

#ifndef OPENVC_CONFIG_MULTIPLE_INSTANCES_ENABLE
#define OPENVC_CONFIG_MULTIPLE_INSTANCES_ENABLE 0
#endif

#ifndef OPENVC_CONFIG_BUILTIN_MBEDTLS_ENABLE
#define OPENVC_CONFIG_BUILTIN_MBEDTLS_ENABLE 1
#endif

#ifndef OPENVC_CONFIG_ECDSA_ENABLE
#define OPENVC_CONFIG_ECDSA_ENABLE 0
#endif

#ifndef OPENVC_CONFIG_HEAP_INTERNAL_SIZE
#if OPENVC_CONFIG_COAP_SECURE_API_ENABLE
#define OPENVC_CONFIG_HEAP_INTERNAL_SIZE (3072 * sizeof(void *))
#else
#define OPENVC_CONFIG_HEAP_INTERNAL_SIZE (1568 * sizeof(void *))
#endif
#endif

#ifndef OPENVC_CONFIG_HEAP_INTERNAL_SIZE_NO_DTLS
#define OPENVC_CONFIG_HEAP_INTERNAL_SIZE_NO_DTLS 384
#endif

#ifndef OPENVC_CONFIG_DTLS_APPLICATION_DATA_MAX_LENGTH
#define OPENVC_CONFIG_DTLS_APPLICATION_DATA_MAX_LENGTH 1400
#endif

#ifndef OPENVC_CONFIG_STACK_VERSION_REV
#define OPENVC_CONFIG_STACK_VERSION_REV 0
#endif

#ifndef OPENVC_CONFIG_STACK_VERSION_MAJOR
#define OPENVC_CONFIG_STACK_VERSION_MAJOR 0
#endif

#ifndef OPENVC_CONFIG_STACK_VERSION_MINOR
#define OPENVC_CONFIG_STACK_VERSION_MINOR 1
#endif

#ifndef OPENVC_CONFIG_DEBUG_UART_ENABLE
#define OPENVC_CONFIG_DEBUG_UART_ENABLE 0
#endif

#endif // OPENVC_CORE_DEFAULT_CONFIG_H_
