#ifndef CONFIG_PLATFORM_H_
#define CONFIG_PLATFORM_H_

#ifndef OPENVC_CONFIG_PLATFORM_INFO
#define OPENVC_CONFIG_PLATFORM_INFO "NONE"
#endif

#ifndef OPENVC_CONFIG_PLATFORM_MESSAGE_MANAGEMENT
#define OPENVC_CONFIG_PLATFORM_MESSAGE_MANAGEMENT 0
#endif

#ifndef OPENVC_CONFIG_PLATFORM_ASSERT_MANAGEMENT
#define OPENVC_CONFIG_PLATFORM_ASSERT_MANAGEMENT 0
#endif

#ifndef OPENVC_CONFIG_PLATFORM_USEC_TIMER_ENABLE
#define OPENVC_CONFIG_PLATFORM_USEC_TIMER_ENABLE 0
#endif

#endif /* CONFIG_PLATFORM_H_ */
