#ifndef OPENVC_CORE_POSIX_CONFIG_H_
#define OPENVC_CORE_POSIX_CONFIG_H_

#define OPENVC_CONFIG_PLATFORM_INFO "POSIX"

#ifndef OPENVC_CONFIG_LOG_OUTPUT
#define OPENVC_CONFIG_LOG_OUTPUT OPENVC_CONFIG_LOG_OUTPUT_PLATFORM_DEFINED
#endif

#define OPENVC_CONFIG_PLATFORM_USEC_TIMER_ENABLE 1

#endif // OPENVC_CORE_POSIX_CONFIG_H_
